[package]
name = "roguelike"
version = "0.1.0"
authors = ["Boxfort <jackwanderson@protonmail.com>"]
edition = "2018"

[dependencies]
rltk = "0.6.2"
specs = { version = "0.15.0" }
specs-derive = "0.4.0"
